export const SlideData = [
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149164/portfolio/waves_l0bkzh.jpg"
    },
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149161/portfolio/karate_kkxb2l.jpg"
    },
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149162/portfolio/Basketball_draw.jpeg_w3dzrn.jpg"
    },
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149161/portfolio/Face_Wardrobe_tklbgw.jpg"
    },
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149160/portfolio/ski_epwcw8.jpg"
    },
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149160/portfolio/hungry_ep8nwk.jpg"
    },
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149323/portfolio/hand_pvcfqb.jpg"
    },
    {
      image:
        "https://res.cloudinary.com/dmbkzjwzq/image/upload/v1649149160/portfolio/flower_b0hrp3.jpg"
    }
  ];